[package]
name = "fin-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
clap = {version = "4.5.53", features = ["derive"]}
thiserror = "2.0.17"

[dev-dependencies]
hex-literal = "1.1.0"
